### ISSUE TITLE
"lib/index.js" not found

### ISSUE THREAD

**Issue by sungwoncho** [glennreyes/react-countup#1]
Using the latest version v1.1.6, when I require the component, I get that

    "lib/index.js" in /Users/mikecho/dev/my_project/node_modules/react-countup/package.json (web.browser)

I am requiring the component like this:

    import CountUp from 'react-countup';

When I look inside `/Users/mikecho/dev/my_project/node_modules/react-countup/`, I don't see `/lib`. But that directory should have been built by babel. What would be the cause of this?

**Comment by glennreyes** [comment]
Thanks for filing that issue! I forgot to add the `files` field in `package.json` to specify which  [files to include to the project](https://docs.npmjs.com/files/package.json#files) in the npm registry. Sorry for that!

[This commit](https://github.com/glennreyes/react-countup/commit/26e34cba8c3225b5d984afe437cdd37d2ecbd5de) fixes it, simply uninstall and install  `v1.1.7`
