### ISSUE TITLE
How to show the numbers in Indian Number System

### ISSUE THREAD

**Issue by nidhinkumar06** [glennreyes/react-countup#102]
I have tried the plugin in which i would like to show the separators in thousands like below

Expected output:  2,99,54,555
Actual Output Receving:  29,954,555

How can i show it in Indian number system

**Comment by glennreyes** [comment]
Since this is a React wrapper please file an issue of the underlying [CountUp.js](https://github.com/inorganik/CountUp.js) repo for this. Thanks!
