### ISSUE TITLE
Is there an easy way I can change the <span> rendered to a <tspan>? (count up is in an svg)

### ISSUE THREAD

**Issue by red-coat** [glennreyes/react-countup#110]
Im rendering my countup in an svg and need to use a tspan instead of a span, could we get a prop to choose which element we render or similar?

**Comment by glennreyes** [comment]
Hey @andy3wood!

For now, you can use it as a render prop component: https://github.com/glennreyes/react-countup#render-prop-example

Other than that, @reakAleek is working on a dedicated hook API (#101) which will work without any html wrapper.

**Comment by andy3wood** [comment]
hey @glennreyes Im not sure this will help me see my current example
`class CircularProgress extends Component {
  render() {
    const {
      percentage, size, transition, className,
    } = this.props;

    return (
      <CircularProgressbar
        text={(
          <CountUp
            end={percentage}
            suffix="%"
            duration={4}
          >
            {({ countUpRef }) => (
              <tspan ref={countUpRef} />
            )}
          </CountUp>
        )}`

I m getting this error in the console 'Warning: Couldn't find attached element to hook the CountUp instance into! Try to attach "containerRef" from the render prop to a an HTMLElement, eg. <span ref={containerRef} />.'

**Comment by whitecrownclown** [comment]
@andy3wood Should be exactly as @glennreyes said, using a render prop.
You can have a look at this [sandbox](https://codesandbox.io/s/qq83y1xl7j). I'm unsure about the warning though, at first glance it seems to be a bug.

**Comment by andy3wood** [comment]
So I found the issue you absolutely must have the delay={0}
I am still getting this error in the console though: warning.js:34 Warning: Couldn't find attached element to hook the CountUp instance into! Try to attach "containerRef" from the render prop to a an HTMLElement, eg. <span ref={containerRef} />.
thanks guys

**Comment by andy3wood** [comment]
here you might actually want to check out that console warning: https://codesandbox.io/s/1rrlq6wrnj

**Comment by reakAleek** [comment]
hey @andy3wood since your example was using react `16.8.0`.... With the latest version of `react-countup:4.1.0` you can use the new hook api.
This way the error can be avoided. I modified your example to show how it is used!
https://codesandbox.io/s/xp3nk9o9lw

**Comment by red-coat** [comment]
hey @reakAleek thanks for your input, i tried your solution but i am getting this error: TypeError: Object(...) is not a function
Im using React version 16.7.0 in my prod, have React only implemented hooks in 16.8.0?

**Comment by reakAleek** [comment]
yeah. hooks were released in 16.8.0

**Comment by red-coat** [comment]
Ok thanks guys, appreciate it!
