### ISSUE TITLE
Can't perform a React state update on an unmounted component.

### ISSUE THREAD

**Issue by bargangilo** [glennreyes/react-countup#113]
Hello,

So I'm having an issue with receiving a state update error on my component with the useCounter hook.

Here's the class:

```
const SavingsCounter = ({ classes }) => {
  let timerId = null;

  const getCurrentMoneySaved = () => {
    // returns number
  };

  const { countUp, update } = useCountUp({
    start: getCurrentMoneySaved() - 245,
    end: getCurrentMoneySaved(),
    duration: 8,
    separator: ',',
    onReset: () => console.log('Resetted!'),
    onUpdate: () => console.log('Updated!'),
    onPauseResume: () => console.log('Paused or resumed!'),
    onStart: ({ }) => console.log('start'),
    onEnd: ({ }) => console.log('end'),
  }, []);

  const updateCounter = () => {
    update(getCurrentMoneySaved());

    // random timeout in 10 - 20 seconds
    timerId = setTimeout(updateCounter, random(10000, 20000));
  };

  useEffect(() => {
    updateCounter();

    return function cleanup() {
      clearTimeout(timerId);
    };
  }, []);

  return (
    <div className={classes.savingsWrapper}>
      <Media query="(max-width: 960px)">
        {
          (matches) => {
            const menu = matches ? (
              <>
                <Typography variant="h4" color="inherit">
                  $
                  { countUp }
                </Typography>
                <Typography variant="h5" color="inherit">
                   Saved in Commissions
                </Typography>
              </>
            ) : (
              <>
                <Typography variant="h5" color="inherit">
                Clever has saved homeowners
                </Typography>
                <Typography variant="h4" color="inherit">
                  $
                  { countUp }
                </Typography>
                <Typography variant="h5" color="inherit">
                  in commissions and counting.
                </Typography>
              </>
            );
            return menu;
          }
        }
      </Media>
    </div>
  );
};
```

Every time I leave the page I get the "state update on an unmounted component" error and then the logs:
end 
end

It seems like something is holding onto a reference of the component and doing an update after the page is unmounted. I couldn't find any way to unsubscribe from anything in react count up, and I'm canceling the timer I have set.

I'm using reach router if it makes any difference. 

Thanks!

**Comment by reakAleek** [comment]
Hi @bargangilo thank you for reporting this issue. I already created a pull request, which will fix the problem. We just need to wait for @glennreyes to publish the fix.

**Comment by bargangilo** [comment]
@reakaleek Sorry to chime in here again. I still seem to be getting the error, is there additional cleanup that I need to kick off in my cleanup function?

**Comment by glennreyes** [comment]
Could you pls paste a snippet of the error message?

**Comment by bargangilo** [comment]
@glennreyes here is the error message. The component code is still the same as above.
```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    in SavingsCounter (created by WithStyles(SavingsCounter))
```

**Comment by bargangilo** [comment]
Also I'll add: 
- Using Gatsby.js (which uses reach router under the hood I believe)
- The error occurs when I navigate away from a page with count-up on it

**Comment by bargangilo** [comment]
@glennreyes Do we have any idea what's going on with the unmount issue? I could potentially take a crack at solving it and shoot you a PR if that would be helpful.

**Comment by glennreyes** [comment]
Hey @bargangilo! Thanks for bringing it up again. Definitely open up a PR if you have something that would fix it. Thank you! 🙏

**Comment by Nfinished** [comment]
Hi, sorry to resurrect this issue but I'm experiencing it on the latest version.

component is essentially

```js
const MyComponent = () => {
  const value = useSelector(MySelector)
  const { countUp, update } = useCountUp({ start: value, end: value, duration: 0.75 })

  useEffect(() => {
    update(value)
  }, [update, value])

  return <div>{countUp</div>
}
```

I've tried some silly things like wrapping update in a setTimeout and clearing in the return, and just returning the reset function, but neither worked.

**Comment by Nfinished** [comment]
After a little bit more testing it seems like the useEffect is irrelevant, the warning is coming from countUp's initialization.

**Comment by nsc-wuhan** [comment]
> Hi, sorry to resurrect this issue but I'm experiencing it on the latest version.
> 
> component is essentially
> 
> ```js
> const MyComponent = () => {
>   const value = useSelector(MySelector)
>   const { countUp, update } = useCountUp({ start: value, end: value, duration: 0.75 })
> 
>   useEffect(() => {
>     update(value)
>   }, [update, value])
> 
>   return <div>{countUp}</div>
> }
> ```
> 
> I've tried some silly things like wrapping update in a setTimeout and clearing in the return, and just returning the reset function, but neither worked.

delay properties need to be set to a suitable value
