### ISSUE TITLE
Support CountUp 2.0

### ISSUE THREAD

**Issue by inorganik** [glennreyes/react-countup#115]
I recently released CountUp 2.0 and it would be cool if this project supported it.

New in 2.0:
- Rewritten in Typescript (distributed code is still javascript)
- New, cleaner method signature
- Jest tests
- Smart easing

https://github.com/inorganik/countUp.js

Thanks!

**Comment by glennreyes** [comment]
Was about time! 😎

While migrating to 2.0, I think it's a good idea to migrate this project to Typescript as well (Ref #109).

**Comment by mmarkelov** [comment]
Migrated to **CountUp 2.0** in **react-countup@5.0.0-0**
