### ISSUE TITLE
Cannot set `duration` to `0`

### ISSUE THREAD

**Issue by whitecrownclown** [glennreyes/react-countup#116]
**Use case:**
I have a counter that increases until a goal is reached. After that I want the counter to go to a value instantly.

Current *workaround* : Use a value close enough to `0`.

**Expected behavior:**
The counter should reach the value instantly when using `duration={0}`

**Actual behavior:**
The counter uses the default value instead (2, I believe).

A sandbox that shows this behavior [here](https://codesandbox.io/s/7ylzz0z0z6) using the hook API.

**Comment by reakaleek** [comment]
hey @whitecrownclown thanks for reporting this, this seems to be a bug in the original countup.js library in the version `1.9.x`.. We'll be upgrading to `2.x.x` soon, which will solve this issue.

**Comment by mmarkelov** [comment]
should be fixed in **react-countup@5.0.0-0**
