### ISSUE TITLE
useCountUp Hook not updating when end changes

### ISSUE THREAD

**Issue by stevez86** [glennreyes/react-countup#117]
I'm getting different values for when I use the Component <CountUp /> vs when I use the hook. The hook doesn't seem to update as expected when the end property changes. For my situation, I set end and then quickly change it before it's finished animating. Here's my code that gives 2 different values:

```
import CountUp, { useCountUp } from 'react-countup';

const Progress = ({ progress, ...otherProps }) => {
  const { countUp } = useCountUp({ end: progress });
  return (
    <>
      <div>{countUp}</div>
      <div><CountUp end={progress} /></div>
    </>
  );
};
```

**Comment by reakaleek** [comment]
Hey @stevez86. Even though this could be an issue.. the recommended way to update the end value is to use the `update` function, which accepts the new end value as param.

here's a minimal example where both hook and component have the same behavior.
https://stackblitz.com/edit/react-ynm277

**Comment by Nfinished** [comment]
I was also just confused by this. Maybe the readme should be updated to reflect this?
