### ISSUE TITLE
Setting easingFn

### ISSUE THREAD

**Issue by MareliBasson** [glennreyes/react-countup#120]
Can someone please provide an example of how to set easingFn to one of the other Robert Penner ease options?

I'm currently at a loss for how to do it, as I can't find an example of the preferred format in the code itself or in the documentation.

**Comment by mmarkelov** [comment]
@MareliBasson like so:
[![Edit react-countup easingFn](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/new-wind-7ov0f?fontsize=14)
More info: [here1](https://github.com/glennreyes/react-countup#easingfn-t-number-b-number-c-number-d-number--number), [here2](https://github.com/danro/jquery-easing/blob/master/jquery.easing.js) and [here](https://inorganik.github.io/countUp.js/)

**Comment by MareliBasson** [comment]
@mmarkelov thanks so much. 

Your example and the last link helped to clear up the confusion :D
