### ISSUE TITLE
Option to redraw to new value?

### ISSUE THREAD

**Issue by mrlubos** [glennreyes/react-countup#122]
Hi, I think it would be super useful to have an option to start every new animation from previously ended number. For example, if I set the end number to `10`, `20`, `30`, and `0` respectively, the `CountUp` component would perform the following animations.

1. 0 to 10
2. 10 to 20
3. 20 to 30
4. 30 to 0

What do you think? You already keep track of the start state, so it should be simple to implement. Otherwise, there is an additional overhead required in the parent component to maintain this state.

**Comment by glennreyes** [comment]
Hey, sounds great! Do you want to open a PR for this feature? Also, do you have any suggestion of how to call the prop? Maybe something like `preserveValue`?
