### ISSUE TITLE
Option to use local formatting?

### ISSUE THREAD

**Issue by mrlubos** [glennreyes/react-countup#123]
Since browsers have a good support for [`Number​.prototype​.toLocale​String()`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString), it would be good to have this as an option or perhaps even a default. Otherwise, I have to currently do

```jsx
<CountUp formattingFn={num => num.toLocaleString()}>
```

which does not look as good.

**Comment by glennreyes** [comment]
Yes that's a great idea, wanna open a PR adding this?

**Comment by mmarkelov** [comment]
As for me I think that using **formattingFn** prop is just fine for this. Cause there are options for [`Number​.prototype​.toLocale​String()`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString)
