### ISSUE TITLE
Noticeable delay even when one isn't set

### ISSUE THREAD

**Issue by tremby** [glennreyes/react-countup#152]
I'm using the hook version. I'm setting `end`, `prefix`, `decimals`, `duration: 3`, and `onStart` to log a message.

Though I've set no delay (I've added some traces in the source code and it's set to `null`) I'm getting a noticeable delay between my intersectionobserver noticing the component is in view (this is when I run the `start()` method, and log something to console) and seeing the numbers change on screen. Any idea what could be causing this?

I can't actually figure out how to _not_ have it start on page load while using the hook. Maybe it's related?

**Comment by mmarkelov** [comment]
close it as stale issue, pls feel free to reopen it if you faced this issue again
