### ISSUE TITLE
Is there a callback for each time the number iterates and changes?

### ISSUE THREAD

**Issue by BenQuirk** [glennreyes/react-countup#164]
First off, this is a cool React project, thank you for making it. I was able to get it to work pretty much instantely. 

Scenario: I have a temperature app I'm building, and after it makes an API request to get the temperature, I pass that value to react-countup and it counts up the number from zero to the current temperature.

What I'm trying to do: At each iteration in the count, I'm looking to run a callback method that passes that value to another function (ultimately to do something like change the shade of a color in real time as the counter is counting up.)

What I tried: I thought onUpdate was what I wanted but after getting that to work it looks like it means on updating the final value (like changing the end point from 50 to 100), not on each update of the number as it gets to the final value (51, 52, 53, etc)

Any idea on how I might grab that value as it counts up?

**Comment by BenQuirk** [comment]
I've figured out a way to accomplish this with mutation observers. 

`{<CountUp 
  start={0}
  end={100} 
  duration={5}
  delay={0.25}
  onStart={this.onCounterUpdate}
  className="Good-Lord'
/>}`


Once the counter starts, it runs this function which creates a mutation observer that watches for the inner text content of the element with className 'Good-Lord', and pass it to our state.  

    onCounterUpdate() {

        const that = this

        console.log('onCounterUpdate running...')

        //More Details https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver
        // Select the node that will be observed for mutations
        const targetNode = document.getElementsByClassName('Good-Lord')[0]

        // Options for the observer (which mutations to observe)
        const config = { attributes: true, childList: true, subtree: true };

        // Callback function to execute when mutations are observed
        const callback = function(mutationsList, observer) {
            for (let mutation of mutationsList) {
                if (mutation.type === 'childList') {
                    console.log(targetNode.innerText)
                    that.setState({ numberWatch: targetNode.innerText})
                } else if (mutation.type === 'attributes') {
                    console.log('The ' + mutation.attributeName + ' attribute was modified.');
                }
            }
        };

        // Create an observer instance linked to the callback function
        const observer = new MutationObserver(callback);

        // Start observing the target node for configured mutations
        observer.observe(targetNode, config);

  }

**Comment by mmarkelov** [comment]
@BenQuirk I am not sure that it will be good approach, especially when you update your state so often. Why don't you want to use simple css animation for this purpose? 
Here is sandbox example:
[![Edit purple-surf-mwkqw](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/purple-surf-mwkqw?fontsize=14)

**Comment by BenQuirk** [comment]
Thanks for taking the time to respond @mmarkelov. 

As the number counts, I'm going to be using that value to do other things on the page as it changes, so that way, the counting of the number and the changes on the page are entirely in sync. So for instance, in my temperature app (really just a prototype for fun), as it counts the temperature up from 0 to 90 degrees, I have a bar chart with a bar whose height changes from 0vh to 1 vh to 2vh ...to 90vh, and it does this perfectly in sync with the countup feature because the value is being updated at the same time. 

Luckily, so far, this mutation observer approach fits my needs.

**Comment by mmarkelov** [comment]
@BenQuirk I just have updated sandbox example, I add some comments to help you understand: 
[![Edit purple-surf-mwkqw](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/purple-surf-mwkqw?fontsize=14)

If you need to sync counter and animations, start and end values are all you need.
So, I try to explain:
1. For counter animation, you know **duration** , **start** and **end** values. Also it is using easeIn animation under hood:
https://github.com/inorganik/countUp.js/blob/16a1b408aeea7a735f0977ffb4d7f643035a76a6/src/countUp.ts#L274-L275
Also you can check some extra details [here](https://github.com/glennreyes/react-countup#easingfn-t-number-b-number-c-number-d-number--number)
2. All you need to use same ease function for you transition animations. You can make them [here](https://matthewlein.com/tools/ceaser)

Mutation observer will work, but it will be really bad UX, cause you do so many overhead jobs, so I think you should KISS(keep it simple stupid)

**Comment by mmarkelov** [comment]
Closed due to inactivity
