### ISSUE TITLE
`preserveValue` doesn't work with `prefix` or `suffix`

### ISSUE THREAD

**Issue by pzi** [glennreyes/react-countup#172]
Hi,

1st: Thanks for your package!

Using `CountUp` quite a lot for a dashboard view I am working on and noticed that when using `preserveValue` the `prefix` and `suffix` flags are causing it to still reset to the start value.

Example: https://codesandbox.io/embed/relaxed-https-3965v

```jsx
  <div className="App">
      <p>
        Without suffix:{" "}<CountUp start={0} end={count} delay={1} preserveValue={true} />
      </p>
      <p>
        With suffix:{" "}<CountUp start={0} end={count} delay={1} suffix={"%"} preserveValue={true}/>
      </p>
      <p>
        With prefix:{" "}<CountUp start={0} end={count} delay={1} prefix={"$"} preserveValue={true}/>
      </p>
      <p>
        With decimals:{" "}<CountUp start={0} end={count} delay={1} decimals={1} preserveValue={true}/>
      </p>
      <p>
        <button onClick={() => setCount(count + 50)}>Add 50</button>{" "}
        <button onClick={() => setCount(count - 50)}>Subtract 50</button>{" "}
        <button onClick={() => setCount(count + 0.5)}>Add 0.5</button>
      </p>
    </div>
```

This also explains the issue I commented on yesterday: https://github.com/glennreyes/react-countup/pull/148#issuecomment-530717894

For now I can get around it by adding the pre-/suffix myself and it's obviously not a show-stopper. Just something to be aware of.

Hope this helps. Thanks for your time.

Cheers
Patrik

**Comment by mmarkelov** [comment]
Thanks a lot, @pzi! I'll take a look

**Comment by musme** [comment]
Здравствуйте, скажите, пожалуйста, почему при установке пакета с npm по-прежнему не работает preserveValue, если есть свойства prefix/suffix?

**Comment by mmarkelov** [comment]
@musme только что вышла версия **v4.2.3** попробуйте ее
