### ISSUE TITLE
Using -1 as target element in useCountUp breaks in test

### ISSUE THREAD

**Issue by RobinBressan** [glennreyes/react-countup#185]
Hi,

I'm trying to have storyshot running and my components using `react-countup` are breaking tests because `countup.js` try to set innerHTML on `-1`.

Maybe you should pass an empty litteral object in here:
https://github.com/glennreyes/react-countup/blob/718eb2cc3422d1e045896b30e14fc7503983f017/src/useCountUp.js#L7

But not sure why this is triggering an error only in tests, it seems triggered inside `react-test-renderer`.

Do you have some feedback on this?

Thank you very much for your time and work!

**Comment by mmarkelov** [comment]
@RobinBressan I can take a look, but it will be helpful if you could provide your code, that breaking tests

**Comment by glennreyes** [comment]
Maybe @reakaleek have an idea how to solve this? As far as I can remember can this be any truthy value that is not an actual element.

**Comment by reakaleek** [comment]
yeah, the `-1` thing, is obviously a hack, to avoid creating a mock element with `document.createElement` every time. 
But we could actually create an element once and just pass the same instance every time to fix this

**Comment by mmarkelov** [comment]
@RobinBressan should be fixed in **v4.2.3**
