### ISSUE TITLE
is `useCountUp` removed in 4.2.5 ?

### ISSUE THREAD

**Issue by geryit** [glennreyes/react-countup#234]

**Comment by mmarkelov** [comment]
@geryit it was some issues with ts definition. Could please check **4.2.6** version?

**Comment by geryit** [comment]
@mmarkelov yes with ts definition. I upgraded to 4.2.6 but now I see this:
<img width="1631" alt="Screen Shot 2019-12-10 at 9 15 53 AM" src="https://user-images.githubusercontent.com/514149/70504130-befdbe00-1b2d-11ea-940f-e65d30259b37.png">

Can you add `start` to definitions too?

**Comment by mmarkelov** [comment]
@geryit thank you! I'll try to fix it today :(
