### ISSUE TITLE
JSX element type 'CountUp' does not have any construct or call signatures.

### ISSUE THREAD

**Issue by apuntovanini** [glennreyes/react-countup#235]
WIth simple usage and latest version with typings it raises this error.

```javascript
import CountUp from 'react-countup';

<CountUp
  start={0}
  end={difference}
  decimals={3}
  suffix="%"
  formattingFn={value => format(value, 'percent')}
/>
```

**Comment by mmarkelov** [comment]
@apuntovanini it was some issues with ts definition. Could please check **4.2.6** version?

**Comment by apuntovanini** [comment]
Yes! Ts error is gone with 4.2.6, thanks!

**Comment by drethedevjs** [comment]
Hi, This is still an issue. I tried 4.2.6 and the latest version.
