### ISSUE TITLE
useCountup seems to start on mount rather that only when start() is called

### ISSUE THREAD

**Issue by dahaca** [glennreyes/react-countup#237]
I have the hook in a component, where I call `start()` from a scroll listener and it works perfectly fine. However, I have noticed that it starts on mount too. And the hook itself simply resets and starts the countUp again on `start()`. Is it planned/possible to make it start only on `start()`? And maybe there is a way to prevent that behavior? It just feels weird to run an unwanted process in the background and do a hundred of re-renders of the parent component

**Comment by mmarkelov** [comment]
@dahaca small repro will be very useful

**Comment by dahaca** [comment]
@mmarkelov So you suggest that that's not the intended behavior of the current implementation? I looked at the source of the hook and the `start()` method, or rather [`restart()`](https://github.com/glennreyes/react-countup/blob/affb4eca9b2413b93c4a32a9b9cefc1f305a6ca0/src/useCountUp.js#L43), is `reset()` and `start()` and [on mount ](https://github.com/glennreyes/react-countup/blob/affb4eca9b2413b93c4a32a9b9cefc1f305a6ca0/src/useCountUp.js#L68) the `start()` is called too. Am I missing something?

**Comment by mmarkelov** [comment]
@dahaca seems like you are right. And hook calls **start** **on mount**. And as for me, I think it should be same as render prop [implementation](https://github.com/glennreyes/react-countup#render-prop-example).
```javascript
     <CountUp start={0} end={100}>
        {({ countUpRef, start }) => (
          <div>
            <span ref={countUpRef} />
            <button onClick={start}>Start</button>
          </div>
        )}
      </CountUp>
```

What do you think?

**Comment by dahaca** [comment]
@mmarkelov It seems like the render props version with `start()` is not running on mount! Only when you click the button. I think it is counterintuitive to have that on mount by default with no possibility to change it. The hook makes it much easier to work with the `start()` method and execute inside `useEffect`. Might be still handy for some, so why not adding an `autostart: boolean` prop to the hook? And then in `useEffect` start is if `autostart === true`? Else not do anything and wait for the `start()` to be called.

**Comment by mmarkelov** [comment]
@dahaca that's make sense for me. I'll try to implement it soon

**Comment by mmarkelov** [comment]
@dahaca I just publish **4.3.0** version and add **startOnMount** prop for your purpose. You can check it out! Thanks!

**Comment by dahaca** [comment]
Perfect! I'm sure others will be thankful for that too :)
