### ISSUE TITLE
the index.d.ts

### ISSUE THREAD

**Issue by BKx201** [glennreyes/react-countup#242]
`type countUpHook = (
  useCountUpProps,
) => {
  countUp: number | string;
  onReset: () => void;
  nUpdate: () => void;
  onPauseResume: () => void;
  onStart: ({ pauseResume }) => void;
  onEnd: ({ pauseResume }) => void;
};`
not have `update`

**Comment by mmarkelov** [comment]
@BKx201 yeah! There is pr to fix it #240 
I'm planning to merge it and publish new version in few days. Thanks!

**Comment by mmarkelov** [comment]
@BKx201 Must be fixed in **4.3.0**

**Comment by daggmano** [comment]
Also getting a heap of implicit 'any' warnings on the parameters of events (onEnd, onStart, etc). Can these either have types applied or (at minimum) explicit 'any' types added?
