### ISSUE TITLE
Decimal support for hook 

### ISSUE THREAD

**Issue by byilagan** [glennreyes/react-countup#259]
Is there a way to change how many decimal places you can show when using the hook?

**Comment by mmarkelov** [comment]
@byilagan you can use [decimals](https://github.com/glennreyes/react-countup#decimals-number) prop:
```javascript
  const { countUp } = useCountUp({ end: 1234567, decimals: 3 });

  return (
      <div>{countUp}</div>
  );
```

**Comment by byilagan** [comment]
@mmarkelov Looks like decimals is not the "useCountUpProps" type and is not supported when I tried to use it (unless I'm using an old version).

**Comment by mmarkelov** [comment]
@ yeah! I suppose I understand what are you talking about. I'll fix it soon
