### ISSUE TITLE
In Mobile View it's showing NaN

### ISSUE THREAD

**Issue by subramanyam0511** [glennreyes/react-countup#260]

**Comment by mmarkelov** [comment]
@subramanyam0511 could you provide details about issue?

**Comment by subramanyam0511** [comment]
![Screenshot from 2020-01-13 14-14-53](https://user-images.githubusercontent.com/50238261/72242326-24ead300-360f-11ea-9306-9f4083a65de0.png)
When i trybto use it in tablet/Mobile ..it's loading as NaN
please provide me solution to config properly

**Comment by muyanli** [comment]
Facing the same issue too

**Comment by affemaen** [comment]
Having the same issue on IOS Safari. Could not reproduce on android.

**Comment by mmarkelov** [comment]
I just need to know details as much as possible about your case

**Comment by gomonx** [comment]
> Hi had this behaviour when I omitted the `duration` prop. Setting the duration fixed it.

it work! >>> Example:  <CountUp duration='0.5'></CountUp>

**Comment by macrozone** [comment]
can confirm that countUp does not work properly without a duration prop

**Comment by vicodinvic1** [comment]
yeah, the same, now you must provide some `string` value to a `duration` prop
