### ISSUE TITLE
separator not showing

### ISSUE THREAD

**Issue by kartboy16** [glennreyes/react-countup#28]
<CountUp 
            start={shortfallBeginning} 
            end={newShortfallFinish} 
            duration={1.0}
            useEasing={true}
            separator=","
            decimal="."
            prefix="$"
            suffix=''
          />

**Comment by kartboy16** [comment]
Solved:  useGrouping={true}

**Comment by glennreyes** [comment]
Cool okay! Feel free to close this issue 👍

**Comment by glennreyes** [comment]
It would probably a good idea to show this prop up to the example, what od you think? @kartboy16

**Comment by kartboy16** [comment]
For sure!

Thanks!  
Alex Hung




On Sun, Sep 11, 2016 at 2:12 AM -0700, "Glenn Reyes" <notifications@github.com> wrote:












It would probably a good idea to show this prop up to the example, what od you think? @kartboy16
