### ISSUE TITLE
onComplete function not working

### ISSUE THREAD

**Issue by FuadAliah** [glennreyes/react-countup#356]
Trying to use onComplete Prop, but it's not working!

**Comment by mmarkelov** [comment]
@FuadAliah there is no **onComplete** prop, there is **onEnd** property

**Comment by FuadAliah** [comment]
Thanks @mmarkelov, I was trying with another plugin Prop (https://www.npmjs.com/package/react-countup/v/2.0.0), thanks for noted, I used onEnd it's working now!
