### ISSUE TITLE
State update doesn't trigger countup to update

### ISSUE THREAD

**Issue by thelamedia** [glennreyes/react-countup#386]
I am trying to use this as a part of a live dashboard, but for some reason, state changes from parent components doesn't trigger an update to useCountUp.  If I use an actual number in the effect update, it triggers correctly, but state updates do not.  Console logging shows that an update occured, but the counter does not adjust.  Code example below:

` const Data = props.data
  const { countUp, start, update } = useCountUp({
    start: 0,
    end: Data(),
    delay: 0,
    duration: 1,
    onUpdate: () => console.log('Updated!'),
  });
  useEffect(() => {
    update(Data())}
    ,[Data, update])`

**Comment by wantToHawaii** [comment]
I have the same issue!
Here is an [example](https://codesandbox.io/s/react-countup-issue-k3d88?file=/src/App.js)
If you try to update child props, count up will not update result value, but the docs says:
**By default, the animation is triggered if any of the following props has changed:**
**duration, end, start**

And thank you for the library, it's useful!

**Comment by mmarkelov** [comment]
@wantToHawaii I know that it is something weird, but for this case you should use provided `update` function:
```js
import React from "react";
import PropTypes from "prop-types";
import { useCountUp } from "react-countup";

const ChildComponent = ({ value }) => {
  const { countUp, update } = useCountUp({ start: 0, end: value, duration: 2 });

  React.useEffect(() => {
    update(value);
  }, [update, value]);

  return (
    <div>
      <div>value without countUp: {value}</div>
      <div>value with countUp: {countUp}</div>
    </div>
  );
};

ChildComponent.propTypes = {
  value: PropTypes.number.isRequired
};

export default ChildComponent;
```

**Comment by lowcrawler** [comment]
The suggested fix does not work.

Specifically, when the ChildComponent is rendered with a 'undefined' prop and then the value gets set...  countUp does not update.

**Comment by mr-niri** [comment]
> The suggested fix does not work.
> 
> Specifically, when the ChildComponent is rendered with a 'undefined' prop and then the value gets set... countUp does not update.
> 
> I was able to kind of get it to work by doing:
> 
> ```
> const { countUp, update } = useCountUp({ end: pending_num ? pending_num : 0, preserveValue: true, duration: 2, suffix:" pending" });
> 
> React.useEffect(() => {
> 		update(pending_num);
> 	  }, [update, pending_num]);
> 
> {typeof pending_num === 'undefined' ? "Getting pending..." : countUp}
> ```
> 
> Unfortunately, every return to this component restarts the countUp (I had hoped the `preserveValue:true` would only have countUp count visibly change when the pending_num changed. :(

you should pass `redraw={true} ` to component as props ,  then it going to render after any render

**Comment by mmarkelov** [comment]
should be ok in **react-countup@5.0.0-0**
