### ISSUE TITLE
onEnd hook fails when the initial start and end are both 0

### ISSUE THREAD

**Issue by Nevin1901** [glennreyes/react-countup#435]
I ran into an issue with the react-countup hook onEnd not being hit when the start value and the end value are both zero.

```
  const { countUp, start, pauseResume, reset, update } = useCountUp({
    start: 0,
    end: 0,
    duration: 3,
    startOnMount: true,
    onUpdate: () => console.log("updated"),
    onEnd: () => console.log("ended"),
  });
```

When you update the hook using the update() function, the onEnd function won't get triggered, even if the value you are updating to is greater than 0.

**Comment by mmarkelov** [comment]
@Nevin1901 I can't reproduce this. Just tried this on [codesandbox](https://codesandbox.io/s/elastic-snyder-l0uxz?file=/src/App.js) and seems to be OK.

**Comment by Nevin1901** [comment]
It must have just been an issue with my code, it's working now for me.
