### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by Luc9802** [glennreyes/react-countup#489]
I see issues pending from a while and the last release done in January 2020. 
So I'm wondering if the project is still maintained or not.

**Comment by mmarkelov** [comment]
@Luc9802 I'm not sure about @glennreyes, but i was busy with some other projects and activities. I can try to find some time to look through issues and pull requests

**Comment by Luc9802** [comment]
@mmarkelov Thank you for your answer, it would be really appreciated to see some fixes done or pull requests accepted!
