### ISSUE TITLE
build run error

### ISSUE THREAD

**Issue by pmg1989** [glennreyes/react-countup#50]
hi, i am install the `react-countup 1.4.0`,and build run this errors:
![image](https://cloud.githubusercontent.com/assets/13361827/23981438/91dbf28e-0a41-11e7-9965-0e5aa36093a4.png)

thanks.

**Comment by glennreyes** [comment]
Hey! Do you think you can install `2.0.3`?

**Comment by glennreyes** [comment]
I'll close this issue for now, feel free to reopen if you're still having issues with it! ;)
