### ISSUE TITLE
[5.0.0] Typescript: 'React' has no exported member named 'Element'

### ISSUE THREAD

**Issue by jlowcs** [glennreyes/react-countup#516]
Hello!

It seems like there is a typing issue in the latest release:
![image](https://user-images.githubusercontent.com/3777724/127029252-ae40a519-9bdf-4b79-b77c-db6c7812a642.png)

What's strange is that I can't seem to find that type in the source code. Maybe it's already fixed on master but not yet released?

**Comment by mmarkelov** [comment]
@jlowcs thanks for your report! Yes, it should be fixed in master. But it wasn't released. I suppose that I'll publish new version on this week. Sorry for that (

**Comment by jlowcs** [comment]
No worries, I appreciate it!

That's only dependabot's fault for creating a PR in our app almost right away 😅

**Comment by xieyezi** [comment]
@jlowcs 
 thanks this repo, it 's great! Please fix it as quickly as possible!  Thanks again!

**Comment by xieyezi** [comment]
@mmarkelov 
thanks this repo, it 's great! Please fix it as quickly as possible! Thanks again!

**Comment by mmarkelov** [comment]
Should be ok in **5.1.0**
