### ISSUE TITLE
Count up animating on every render

### ISSUE THREAD

**Issue by Mikeg542** [glennreyes/react-countup#52]
I'm using this plugin on my dashboard and have a react-select multiselect that whenever I add or remove selections (changing state), it re-renders the countup animation despite start, end and duration being integers. If there is any other code needed, let me know

code: 

const textStyle = {
       color: #f5d512;
}

...

<CountUp style={textStyle} start={0} end={50} duration={2} />

**Comment by glennreyes** [comment]
Hi @Mikeg542! 👋 

It shouldn't re-render except you pass the  `redraw` prop or `start` or `end` value changes. You can check the update policy here: https://github.com/glennreyes/react-countup/blob/master/index.jsx#L99-L105

Does it help?

**Comment by glennreyes** [comment]
I'll close this for now, feel free to reopen if you're still having issues with it! ;)

**Comment by Mikeg542** [comment]
Hey Glenn,

I discovered the problem. I was setting the style to the color in an ENV variable and that was triggered the rerender when the page rerenders. I've moved the style to apply to a parent element and fixed the problem.
