### ISSUE TITLE
Add accessibility for occupation period

### ISSUE THREAD

**Issue by iManu** [glennreyes/react-countup#522]
Hello,
User-agents of assistive technologies may want to wait until the modifications are complete before exposing them to the user.
It would be more efficient if the counter updated its states once the occupation period was over, using `aria-busy` 🙏

**Comment by mmarkelov** [comment]
@iManu i'm okay with this. But honestly I didn’t have much experience with aria attributes and don't know how it should looks like

**Comment by iManu** [comment]
It's a simple attribute, I guess you have to set a state to `false` when counter finished.

Something like this:
```js
return <span aria-live="polite" aria-busy={isBusy} className={className} ref={containerRef} style={style} />;
```

Unfortunately I'm too poor with Typescript for submit a PR, I try but I loose too much time :/ 

Finally, my suggestion is a simple first step to improve accessibility on your component. If you decide to implement it maybe iterations will come in the future…

**Comment by mmarkelov** [comment]
I just thought that it will be easier to give the user ability to control this logic, I made some changes to `CountUp` component and provide an example:

https://github.com/glennreyes/react-countup#set-accessibility-properties-for-occupation-period

**Comment by vincentaudebert** [comment]
Sorry @mmarkelov I post here again because your example isn't correct I think. To be correct, `aria-busy` comes with `aria-live` attribute (probably polite value wanted)

Also may I ask here why there's no unit test for the component version on onEnd attribute?
