### ISSUE TITLE
countup breaks when preserveValue is True with a custom formattingFn

### ISSUE THREAD

**Issue by JustinDrake** [glennreyes/react-countup#529]
Countup stops working when `preserveValue` is `True` and `formattingFn` is set to a custom function.

**Comment by mmarkelov** [comment]
could you provide small representation?

**Comment by codeaid** [comment]
I'm having the same issue. It still works but it always starts counting from `0`.

Here's what I have:

```typescript
const formatCurrency = (value: number, locale: string, currency: string) => 
  new Intl.NumberFormat(locale, {
    currency,
    currencyDisplay: 'symbol',
    minimumFractionDigits: 2,
    style: 'currency',
  }).format(value);
```

```typescript
<CountUp
  duration={3}
  end={value}
  formattingFn={value => formatCurrency(value, locale, 'GBP')}
  preserveValue={true}
/>
```

If `value` goes from positive to negative it starts counting from `0` and down. If it goes from negative from positive then again, as soon as the `value` changes it first becomes `0` and then starts counting up to the `end` value.

**Comment by corinneehrsam** [comment]
Hello, I have a similar issue. I'm trying to add a leading zero, so I wrote a custom formatingFn. But preserveValue doesn't work. It always counts up from 0. What am I doing wrong?

const changeFormat = useCallback((value) => {
    if (value < 10) {
      return "0" + value;
    } else {
      return value;
    }
  }, []);

<CountUp end={postDay} duration={3} preseveValue={true} formattingFn={changeFormat} />
