### ISSUE TITLE
remove react from deps

### ISSUE THREAD

**Issue by AVVS** [glennreyes/react-countup#66]
Hi, please remove react from deps, its already in the peer ones

https://github.com/glennreyes/react-countup/blob/master/package.json#L42

**Comment by glennreyes** [comment]
Good catch, could you send a PR pls?

**Comment by glennreyes** [comment]
Thank you! I solved this [here](https://github.com/glennreyes/react-countup/commit/b916bb52f28a30a60443bcd848d3cf70453c3236)
