### ISSUE TITLE
Hello! I have some problem

### ISSUE THREAD

**Issue by simakovEvgen** [glennreyes/react-countup#68]
When I try to run:
bundle.js:1577 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.

**Comment by glennreyes** [comment]
Hello! Can you reproduce your source code on codesandbox.io? I'd be happy to help! 👍

**Comment by simakovEvgen** [comment]
I use script for build App:
"build": "browserify -t [ babelify --presets [ es2015 react ] --plugins [transform-object-rest-spread] ] ./src/main.jsx -o build/bundle.js"


My Code
https://codesandbox.io/s/oYlwoOvzK

**Comment by glennreyes** [comment]
It should work if you write following instead:
```
import CountUp from 'react-countup';
```
Will investigate on that, thanks for filing this issue!

**Comment by simakovEvgen** [comment]
It work! But I don't understand why it wasn't))) thanks for answer

**Comment by glennreyes** [comment]
It's because the module is written in ES6 and it's being [transformed by Babel 6 to CommonJS](https://babeljs.io/docs/plugins/transform-es2015-modules-commonjs/).
If you prefer writing CommonJS you could also do:
```js
const { default as CountUp } = require('react-countup')
```
👍
