### ISSUE TITLE
Missing/Incomplete Types

### ISSUE THREAD

**Issue by dsbrianwebster** [glennreyes/react-countup#701]
If you A/B the supported props...
https://github.com/glennreyes/react-countup#props

against the actual types...

<img width="726" alt="image" src="https://user-images.githubusercontent.com/8154653/184886391-a0a61e3f-80b3-4cfa-86f9-2181572a3692.png">

You'll note several are missing. For example: separator, decimal, duration, prefix. This is not an exhausted list.

**Comment by mmarkelov** [comment]
I cannot reproduce it, could you please provide some extra details? Cause these missing types are inhereted from **countup** library
