### ISSUE TITLE
missing types

### ISSUE THREAD

**Issue by fantian007** [glennreyes/react-countup#702]
<img width="303" alt="image" src="https://user-images.githubusercontent.com/24759814/186823515-e900dcaf-10ac-43be-ae46-19f3d4c4cfd6.png">

无类型定义，but works

**Comment by mmarkelov** [comment]
I cannot reproduce it, could you please provide some extra details?

**Comment by hrougier** [comment]
Facing a similar issue with missing prop types like `startOnMount`

```tsx
<CountUp
  start={0}
  end={10}
  startOnMount={false}
/>
```

```
TS2322: Type '{ start: number; end: number; startOnMount: boolean; }' is not assignable to type 'IntrinsicAttributes & CountUpProps'.
Property 'startOnMount' does not exist on type 'IntrinsicAttributes & CountUpProps'.
```

**Comment by mmarkelov** [comment]
> Facing a similar issue with missing prop types like `startOnMount`
> 
> ```tsx
> <CountUp
>   start={0}
>   end={10}
>   startOnMount={false}
> />
> ```
> 
> ```
> TS2322: Type '{ start: number; end: number; startOnMount: boolean; }' is not assignable to type 'IntrinsicAttributes & CountUpProps'.
> Property 'startOnMount' does not exist on type 'IntrinsicAttributes & CountUpProps'.
> ```

`startOnMount` prop is used only for counter created with hook
