### ISSUE TITLE
Separator not present in start value

### ISSUE THREAD

**Issue by tomkelsey** [glennreyes/react-countup#71]
Hey,

Thanks for making this react component - I've found it really useful 👍

CountUp looks like it kicks in when the component mounts and, before then, it just renders the specified start value.

Unfortunately this means if you render stuff on the server, you'll get a flash of e.g. "10000" before the component mounts and it changes to "10,000"

I'm not sure what the best fix to this problem would be.

Perhaps a simple function that renders the start value with the separator before CountUp kicks in?

**Comment by glennreyes** [comment]
Hey @tomkelsey thanks for filing this!

Yeah we should totally render all extra characters (which are `decimal`, `separator`, `prefix`, `suffix`) correctly. A simple function that formats the figure correctly for SSR lgtm.

If you open a PR for this I & many others would be really grateful!
