### ISSUE TITLE
useEasing defaults to undefined instead of true

### ISSUE THREAD

**Issue by solithcy** [glennreyes/react-countup#711]
`useEasing` seems to default to `undefined`, which contradicts the documentation.
This can be seen on https://tr8tk.csb.app.

![Example of useEasing defaulting to false](https://user-images.githubusercontent.com/78880286/188325340-69283f0c-ec1c-4ca4-aa1a-66f3e46c6b49.gif)

Using React DevTools, we can see that the useEasing argument is set to `undefined`.

![React DevTools](https://user-images.githubusercontent.com/78880286/188325447-4d22315b-1cc6-4be8-baa9-35591919d15a.png)

https://github.com/glennreyes/react-countup/blob/1caacde413d9dcad2412d4ead4dd1d9a0ff2f149/README.md?plain=1#L276-L280

**Comment by RoseChilds** [comment]
I've created a CodeSandbox using the latest version of react-countup that makes this more obvious
[Example](https://codesandbox.io/s/react-countup-easingfn-forked-ifvj3w)
