### ISSUE TITLE
No start value on SSR

### ISSUE THREAD

**Issue by hrougier** [glennreyes/react-countup#724]
Pull request #580 fixed an issue where start value was not displayed on Server Side Rendering.
However, if the start value is 0, it is stil not displayed because 0 is a falsy value.

`CountUp.tsx` [line 133]

```ts
{props.start ? getCountUp().formattingFn(props.start) : ''}
```

Could this fix work?

```ts
{typeof props.start === 'number' ? getCountUp().formattingFn(props.start) : ''}
```

**Comment by mmarkelov** [comment]
@hrougier good catch, will fix it
