### ISSUE TITLE
Start animation only when element is on viewport?

### ISSUE THREAD

**Issue by Kotoriii** [glennreyes/react-countup#73]
Hello, love the component! Is there a way to make a CountUp element start the animation only when it is visible in the viewport straight out of the box? Would love to make this functionality work. Thanks :-)

**Comment by Kotoriii** [comment]
Maybe I asked too fas, sorry. Using https://github.com/stutrek/scrollmonitor-react proved to do the trick.

**Comment by helenkapatsa** [comment]
Good solution via 'react-visibility-sensor' provided by Tadas Antanavicius here: https://stackoverflow.com/questions/51044090/react-countup-animation-starts-immediately-after-the-page-loading-should-start

**Comment by AllanPooley** [comment]
Howdy everyone,

Just incase anyone stumbles across this thread looking for a good solution, here's what I ended up with using [react-intersection-observer](https://github.com/thebuilder/react-intersection-observer)

The change in the `start` prop triggers the animation when the component is `inView`.

```jsx
import React from 'react';
import CountUp from 'react-countup';
import { useInView } from 'react-intersection-observer';

const COUNT_UP_START = 1;
const COUNT_UP_DURATION = 5;

const Example = (props) => {
  const {
    targetNumber
  } = props;
  const [ref, inView] = useInView({
    /* Optional options */
    threshold: 0,
    triggerOnce: true,
  });
  return (
    <div className="col col-left col-coffees" ref={ref}>
      <CountUp
        start={inView ? COUNT_UP_START : targetNumber}
        end={targetNumber}
        delay={0}
        duration={COUNT_UP_DURATION}
      >
        {({ countUpRef }) => (
          <span ref={countUpRef} className="outcome-value" />
        )}
      </CountUp>
    </div>
  );
};

export default Example;
```
