### ISSUE TITLE
separator is not working

### ISSUE THREAD

**Issue by tutv95** [glennreyes/react-countup#75]
```
 <CountUp className="CountUp"
                     suffix="+"
                     separator=" "
                     decimals={4}
                     decimal=","
                     start={0} end={total}/>
```

```
//Result: 912800,0000+
//Expected: 912 800,0000+
```

**Comment by tutv95** [comment]
👍  Thanks. It's working now :)

**Comment by tutv95** [comment]
But I think when `separator` is not empty, component CoutuUp will auto detect `useGrouping`

**Comment by glennreyes** [comment]
Yeah seems like a good idea to add this behaviour. Would you mind to open a PR?

PS: if you set useGrouping only, a [default value of `separator`](https://github.com/glennreyes/react-countup/blob/master/src/index.js#L108) will be used.
