### ISSUE TITLE
When suffix and/or prefix are undefined, they get converted to the string 'undefined'

### ISSUE THREAD

**Issue by nevnein** [glennreyes/react-countup#775]
As per title, if the prop `suffix` and/or `prefix` (and possibly other props too?) are `undefined`, they get printed as the string `"undefined"` instead of just being ignored.

Use case: wrapping the CountUp component with another component to limit the API surface. Here's a minimal example/repro: [https://codesandbox.io/s/aged-forest-udseyh?file=/src/App.js](https://codesandbox.io/s/aged-forest-udseyh?file=/src/App.js)

**Comment by mmarkelov** [comment]
@nevnein thanks for report. I'll try to fix it during this week.
Problem is here:
https://github.com/glennreyes/react-countup/blob/f1a5445bbe85669b3d5ae62923f73f73ab5aaa23/src/useCountUp.ts#L37
```js
// props: {suffix: undefined}
{ ...DEFAULTS, ...props } // will override default suffix in thi scenario
```
