### ISSUE TITLE
[Doubt] Use countup without defining end number

### ISSUE THREAD

**Issue by RominaMartin** [glennreyes/react-countup#79]
I want to show the countup component but the `end` number is defined by a response from a request. My idea is to show the numbers changing around while the request is in process and once I get the response leave that number as ending one. I'm not sure if I can do this or how could I get it done.

I apologize if this is not the place to ask this question but I wasn't quite sure on where to do it. Thanks

**Comment by glennreyes** [comment]
Not quite sure if that's possible with CountUp.js since animation speed relies on start, end and duration props. Maybe @inorganik has an idea?

What you could do is to initially render `0` and start animation once you get the response, if that is acceptable.

Otherwise, I'd try to ask at Stackoverflow.

**Comment by inorganik** [comment]
Here's how I would do it with vanilla JS:

First, set some constants:
```js
const minEndVal = 2;
const maxEndVal = 967;
const decimals = 0;
const switchInterval = 0.75; // 3/4 of a second
let lastWasMax = true;
```
Init CountUp with your constants, and pass the option to disable easing. We want the numbers to be changing at a consistent pace while it "scrambles":
```js
let countUp = new CountUp(elem, minEndVal, maxEndVal, decimals, switchInterval, { useEasing: false });
countUp.start();
```
Use an interval to continuously change the endVal, calling `update`, with every other update going in the opposite direction (min, max, min, max, etc.):
```js
let scrambleInterval = setInterval(function() {
  let endVal = (lastWasMax) ? minEndVal : maxEndVal;
  countUp.update(endVal);
  endVal = !endVal;
}, switchInterval);
```
Finally when you have the value you want to end on, re-init countUp so it uses easing. The `frameVal` property of countUp is the current value the counter is at:
```js
  clearInterval(scrambleInterval);
  const whereWeLeftOff = countUp.frameVal;
  let countUp = new CountUp(elem, whereWeLeftOff, finalValue, decimals, 1)
  countUp.update(finalValue);
```
That should do it!

**Comment by RominaMartin** [comment]
Thank you both very much for replying!! I'm going to try and implement it with react.

@glennreyes is the `update` method called the same way for react or it will only update when the state changes?

Thanks again for replying!

**Comment by glennreyes** [comment]
@RominaMartin I don't think so. It will create a new countup instance on every state change, so this should definitely be improved!

**Comment by RominaMartin** [comment]
@glennreyes Oh okay. This means there's no way _at least for now_ to do inorganik's approach with this component? I've been thinking how would I do this but nothing came to my mind yet. Thanks again

**Comment by glennreyes** [comment]
@RominaMartin You could implement what @inorganik explained before in a wrapping React stateful component. So instead of calling `countUp.update()` you would update the state. Does this help?

**Comment by RominaMartin** [comment]
@glennreyes Indeed, it does help. Thanks and sorry for the late reply!
