### ISSUE TITLE
Is there a way to trigger this purely manually? It seems when I do your example, I just restart the animation.

### ISSUE THREAD

**Issue by yuchant** [glennreyes/react-countup#83]
I'm noticing a performance impact of having 6 of these and would like to purely control the start times. After page load and or after scroll into view.

Can you add this feature? To not start autuomatically.

**Comment by glennreyes** [comment]
Is it this what you are looking for? https://github.com/glennreyes/react-countup#manually-start-the-animation

**Comment by yuchant** [comment]
@glennreyes no, technically there is no purely manual way to start the animation.

The animation is hard coded to start on `componentDidMount()`.

Manual start usually implies it doesn't ever start unless manually done so. I hope you add it!

**Comment by glennreyes** [comment]
I'd love to have this behaviour replaced! Would you mind to open a PR that does this? This would also introduce a breaking change.

**Comment by yuchant** [comment]
@glennreyes it doesn't need to be a breaking change if it's a new prop: `startManually`

Probably just check if `startManually` prop set before starting animation.

this.props.startManually ? null: startAnimation(this);

I don't know how to test this component though so I hope you can do it!

**Comment by matueszwin** [comment]
Yes, I have the same problem. 
It starts automatically everytime
