### ISSUE TITLE
[Bug] `startOnMount` does not exist

### ISSUE THREAD

**Issue by severinlandolt** [glennreyes/react-countup#840]
Hey there, I am using `6.5.0` and I cannot set `startOnMount` to false, because of a TS error:

![CleanShot 2024-01-08 at 22 40 02](https://github.com/glennreyes/react-countup/assets/41927988/c9df8c32-5f17-4e25-93a8-62e602459a98)

**Comment by mmarkelov** [comment]
should be fixed in **6.5.2**
