### ISSUE TITLE
CountUp name export could not found on build phase

### ISSUE THREAD

**Issue by violetbee** [glennreyes/react-countup#849]
Error occured on 6.5.1 version.

![image](https://github.com/glennreyes/react-countup/assets/61601796/5409b20f-3fa1-46cd-8716-879ada304132)

**Comment by liyunmeng1** [comment]
![image](https://github.com/glennreyes/react-countup/assets/157443604/f897d3f0-e341-4376-a27d-222b1abe890a)

I'm having the same problem at this moment, did you solve it?

**Comment by thirstycode** [comment]
I'm having same issue

**Comment by thirstycode** [comment]
@liyunmeng1 @violetbee I fixed it temporarily by switching to version 6.5.0

**Comment by mmarkelov** [comment]
Hi guys! So sorry about that, this is because of #848 - I will try to find the way to fix or rollback it. For now you can use 6.5.0 version. Once again sorry :(

**Comment by st3fus** [comment]
> Hi guys! So sorry about that, this is because of #848 - I will try to find the way to fix or rollback it. For now you can use 6.5.0 version. Once again sorry :(

Having the same issue with 6.5.0 :(

**Comment by st3fus** [comment]
> @st3fus that's weird, cause there was not any changes related to build process in 6.5.0, do you mean that you have just the same error as @violetbee ?

My bad, fixed it, works now. Had a "^" before the version number, removed it. Works now.

**Comment by mmarkelov** [comment]
should be fixed in 6.5.2
