### ISSUE TITLE
Count should start after the component is in view.

### ISSUE THREAD

**Issue by Byloor** [glennreyes/react-countup#85]
Is it possible for countup to begin once we scrolldown to the component , currently the count starts as soon as the page is rendered. 
Animation happens only once(which is good)after the page is loaded, but I would like the counter not to begin soon after the page is loaded, but when user scrolls down to the component first time.
My code looks like this:
```
	render() {
	return (
	<div className={style.componentName}>
	<h2>Heading</h2>
	<div className={style.col}>
	<div>My counter</div>
	<CountUp className={style.countup} decimals={1} start={0} end={25} suffix=" %" duration={3} />
	</div>
         </div>)}
```

**Comment by evatd** [comment]
I'm also interested in the above ^. @Byloor , have you solved this by any chance? Cheers

**Comment by Byloor** [comment]
@evatd Yes, Refer : https://stackoverflow.com/questions/51044090/react-countup-animation-starts-immediately-after-the-page-loading-should-start

Refer the answer : ive also updated my question here. Let me know if it works:)

**Comment by Byloor** [comment]
@glennreyes Yes and no. it alone does not help.

**Comment by evatd** [comment]
@Byloor Brilliant, thanks - this works! I ended up combining the package with `react-visibility-sensor` too, but wanted the counter to start only once. Solved with a piece of state, as per your solution  💯

**Comment by aress31** [comment]
Why not adding an option out of the box to React CountUP to handle animation when component is in the viewport? 🤔

**Comment by talk2muhammadawais** [comment]
> @Byloor Brilliant, thanks - this works! I ended up combining the package with `react-visibility-sensor` too, but wanted the counter to run only once. Solved with a piece of state, as per your solution  💯 

Did countup ony run once after come in visibility  of yes please share v9de with me
