### ISSUE TITLE
Failed to resolve import "react-countup/build/CountUp"

### ISSUE THREAD

**Issue by ethan89009** [glennreyes/react-countup#853]
The error shows that you cannot import the CountUp component
![image](https://github.com/glennreyes/react-countup/assets/112543357/d6beda50-13b7-40d3-8633-1df2ca5ca6a0)

**Comment by mmarkelov** [comment]
hello @ethan89009! I cannot understand the way you try to import CountUp. It should be
```js
import './styles.css';
import CountUp, { useCountUp } from 'react-countup';

export default function App() {
  useCountUp({
    ref: 'counter',
    end: 1234567,
    enableScrollSpy: true,
    scrollSpyDelay: 1000,
  });

  return (
    <div className="App">
      <div className="content" />
      <CountUp end={100} enableScrollSpy />
      <br />
      <span id="counter" />
    </div>
  );
}
```

Please try the latest version of library, cause for **6.5.1 - 6.5.2** import might be broken

**Comment by ethan89009** [comment]
Yes i have corrected it but forgot to remove the issue, thanks for clarifying, vs code automatically added that import
