### ISSUE TITLE
Documentation for alpha mixed up in main README

### ISSUE THREAD

**Issue by Floriferous** [glennreyes/react-countup#92]
I tried adding the `delay` prop on CountUp, but it does not do anything, because I was still on v3. It is not clear from the main README that some of the API is currently not yet released.

It might be helpful to explicitly mention what parts of the API are currently available, and which ones are still in alpha/beta. Or if alpha is stable enough, invite users to explicitly install the alpha.

**Comment by glennreyes** [comment]
Yeah good point, thank you! Wanna send a PR doing that?

**Comment by Floriferous** [comment]
When do you plan to release a stable version of v4? And what parts of the API are currently not available in v3?
