### ISSUE TITLE
On React v16 will make some warnings

### ISSUE THREAD

**Issue by zsirfs** [glennreyes/react-countup#94]
Recently GitHub is not working properly. So I can only copy the error message to you.

```
index.js:2177 Warning: Couldn't find attached element to hook the CountUp instance into! Try to attach "containerRef" from the render prop to a an HTMLElement, eg. <span ref={containerRef} />.

```
I checked the API you used after React v16.4, `React.createRef` previous versions of this API cannot be used

**Comment by glennreyes** [comment]
Can you provide an example on CodeSandbox?

**Comment by makis-spy** [comment]
I am encountering this as well. Looking into it

**Comment by zsirfs** [comment]
@glennreyes The examples folds is the v16.3.0 of React.

**Comment by glennreyes** [comment]
If you're on =< 16.3, you may want to use `react-countup@3.0.3`, docs [here](https://github.com/glennreyes/react-countup/tree/d0002932dac8a274f951e53b1d9b1f4719176147).
