### ISSUE TITLE
Update Component value from previous value

### ISSUE THREAD

**Issue by DanielHosseini** [glennreyes/react-countup#96]
Hello,

I'm having diffulities using the update function that is provided. I'm having a function that runs every 10 minutes fetching data from an api. I would like to run the update function for the countUp component every time the data is fetched. I don't want it to restart from 0, rather that It either goes down or up from the value that is already set. Which is the purpose of update I assume.

I managed to run the example that runs the start method on button click, but I would to run the update method when I fetch data from the api.

Could anybody provide an example to get a reference to the component so I will be able run the update method?

**Comment by DanielHosseini** [comment]
Never mind, I'm new to React but I used ref in order to get the instance of the countUp component. After that, I had the possibility to run update method from wherever I wanted. So for example:
`<CountUp ref='test' start={0} end={100} />`

and later i could just use the following to update the component.
`this.refs.this.update(newvalue)`

**Comment by markalfred** [comment]
An alternative solution: I made a small component called `CountTo` that wraps Countup to do this automatically via its `componentWillReceiveProps`.

```jsx
// count-to.jsx
import Countup from 'react-countup';

export default class CountTo extends Component {
  static propTypes = { to: pt.number }
  static defaultProps = { to: 0 }
  state = { from: 0, to: this.props.to }

  componentWillReceiveProps(nextProps) {
    this.setState({
      from: this.props.to, // The "old" target number
      to: nextProps.to, // The "new" target number
    })
  }

  render() {
    return <Countup start={this.state.from} end={this.state.to} />
  }
}
```

You can then use this in your other component, and not worry about using `update` or manually saving off the old state.

```jsx
// my-component.jsx
import CountTo from './count-to'

export default class MyComponent extends React.Component {
  render () {
    return (
      <div>
        <input onChange={event => this.setState({ num: event.target.value })} />
        <CountTo to={this.state.num} />
      </div>
    )
  }
}
```

YMMV but this works better for me than the `update` render prop.

**Comment by glennreyes** [comment]
Closing this. Let me know if there's something we can improve in the lib according to this issue.

**Comment by dickeylth** [comment]
As of the introduction of React Hooks, there's a simple solution:

```
const CountUpMemo = props => {
  const prevValueRef = useRef();
  useEffect(() => {
    prevValueRef.current = props.end;
  });
  return (
    <CountUp
      start={prevValueRef.current}
      end={props.end}
      {...props}
    />
  );
};
```
