### ISSUE TITLE
Snapshot testing warnings: Couldn't find attached element to hook the CountUp instance into!

### ISSUE THREAD

**Issue by marcelhageman** [glennreyes/react-countup#97]
I'm getting this warning message when I run Jest:

`Warning: Couldn't find attached element to hook the CountUp instance into! Try to attach "containerRef" from the render prop to a an HTMLElement, eg. <span ref={containerRef} />.`

It occurs specifically upon creating a snapshot, as such:

```
import renderer from 'react-test-renderer';

describe('Snapshot', () => {
  it('renders correctly the <InvoiceGraph />', () => {
    const tree = renderer
      .create(<InvoiceGraph breakpoint={breakpoint} subscription={20} data={data} />)
      .toJSON();
    expect(tree).toMatchSnapshot();
  });
});

```

In my actual web project this error doesn't occur, just when I use Jest to run tests it starts to throw warnings. It's polluting my test console and I can't seem to clear it up.

In my code I'm using it as follows:

```
<div className="bar__amount">
  {
    amount
      ? <CountUp
        end={amount}
        duration={1}
        delay={randomAnimationTriggerTime / 1000}
        decimals={0}
        prefix="€"
      />
      : <Text
        color="white"
        value="-"
      />
  }
</div>
```

The generated snapshots do look a bit wonky:

```
  <div
    className="bar__amount"
  >
    <span
      className={undefined}
      style={undefined}
    />
  </div>
```

While debugging I found that `this.containerRef.current` is `null` during these snapshot tests. Regular Jest unit tests do work and contain a `HTMLElement`.

I don't know why it's `null` nor how to fix it, though. It seems like the snapshot renderer I'm using doesn't play nice with `ref` or something...

Do you have any insights how to solve this?

**Comment by KristenWilde** [comment]
How should I go about writing a test (with jest and rect-test-renderer) for a component that contains a CountUp component? I wrote a snapshot test as I normally would, but the test fails to run and produces the following error:

```
    You need to pass the CountUp component as an argument!
    eg. this.myCountUp.startAnimation(this.myCountUp);

       7 |
       8 |   it('renders card without pluralize prop', () => {
    >  9 |     const test_instance = renderer.create(
         |                                    ^
```

The component works fine. The code includes:
```
import CountUp from 'react-countup'
...
<strong className="data"><CountUp end={this.props.data} separator="," /></strong>
```

My test:
```
import React from 'react'
import renderer from 'react-test-renderer'
import DataCardLight from 'components/Cards/DataCardLight'

describe('<DataCardLight />', () => {
  test('renders card with pluralize prop', () => {
    const test_instance = renderer.create(
      <DataCardLight icon="users" data={0} units="Reach" pluralize={false}/>
    )
    expect(test_instance.toJSON()).toMatchSnapshot()
  })
})
```

**Comment by emroussel** [comment]
@glennreyes I am getting the same warning as @marcelhageman during jest snapshot tests when using react-countup with render props to render my own element.

Do you have any insight into what is causing the warning to be triggered only during snapshots (renders fine when I run the app)?

**Comment by glennreyes** [comment]
@emroussel That should be fixed in #100. Are you using the current version? Maybe you could create a minimal CodeSandbox sample reproducing the warning?

**Comment by emroussel** [comment]
@glennreyes any updates on this? It seems to me like [this condition](https://github.com/glennreyes/react-countup/blob/master/src/CountUp.js#L91) should be this instead:

```
!(this.containerRef.current instanceof HTMLElement)
```

Any thoughts? Happy to push a PR if you agree.

**Comment by emroussel** [comment]
The condition I mentioned above ended up not being the problem. For future reference, here's what I did to fix it (I had two issues going on at the same time, which made it harder to figure out):
- Mocks refs during snapshot tests (https://reactjs.org/blog/2016/11/16/react-v15.4.0.html#mocking-refs-for-snapshot-testing)
- Update `react-test-renderer` to a version that supports `React.createRef()`

The solution looked something like this:
```js
import React from 'react';
import MyInput from './MyInput';
import renderer from 'react-test-renderer';

function createNodeMock(element) {
  // Need to return an HTMLElement here to remove the error
  return document.createElement(element.type);
}

it('renders correctly', () => {
  const options = { createNodeMock };
  const tree = renderer.create(<MyInput />, options);
  expect(tree).toMatchSnapshot();
});
```
